CREATE DATABASE menu_db;

USE menu_db;

CREATE TABLE items (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(75) NOT NULL,
  description VARCHAR(255) NOT NULL,
  price DOUBLE(4,2) NOT NULL,
  soldout BOOLEAN NOT NULL DEFAULT 0,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);
